<div class="page-title">
    <h1><?php echo $this->__('Current Balance : <Strong> %s %s(s)</strong>', Mage::helper('rewardpoint')->getCurrentUserBalance(), Mage::helper('rewardpoint')->getUnitName()) ?></h1>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php $activities = $this->getHistory(); ?>
<?php if($activities->getSize()): ?>
<?php echo $this->getPagerHtml(); ?>
<table class="data-table" id="my-commission-history">
    <col width="1" />
    <col width="1" />
    <col width="1" />
    <col width="1" />
    <thead>
        <tr>
            <th><?php echo $this->__('ID') ?></th>
            <th><?php echo $this->__('Activity Type') ?></th>
			<th><?php echo $this->__('Time') ?></th>
            <th><?php echo $this->__('Point Earned/Spent') ?></th>
        </tr>
    </thead>
    <tbody>
        <?php $_odd = ''; ?>
        <?php foreach ($activities as $activity): ?>
        <tr>
            <td  class="a-center"><?php echo $activity->getId() ?></td>
            <td  class="a-center"><?php echo Mage::helper('rewardpoint')->getActivityTypeText($activity) ?></td>
			<td  class="a-center"><?php echo $activity->getCreatedAt() ?></td>
			<td  class="a-center"><?php echo $activity->getPointEarned() ?></td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<?php echo $this->getPagerHtml(); ?>
<script type="text/javascript">decorateTable('my-commission-history');</script>
<?php else: ?>
    <p class="note-msg"><?php echo $this->__('No data or deleted.') ?></p>
<?php endif ?>