<div class="box-account">
	<div class="box-head">
		<h2><?php echo $this->__('Config') ?></h2>
	</div>
	<form method="post" id="config_form" action="<?php echo Mage::getUrl('rewardpoint/index/changeConfig') ?>">
		<ul class="form-list">
			<li class="control">
				<input type="checkbox" onchange='changeConfig()' name="receive_email_config" id="receive_email_config" class="checkbox" <?php if(Mage::helper('rewardpoint')->getUserConfig()): ?><?php echo 'checked' ?><?php endif; ?>  /><label for="receive_email_config"><?php echo $this->__('Receive Update Balance Email') ?></label>
			</li>
		</ul>
	</form>
</div>
<script>
	var config = $('receive_email_config');
	var form = new VarienForm('config_form');
	function changeConfig()
	{
		form.submit();
	}
	
</script>