<?php 
	$ruleCollection = Mage::helper('rewardpoint')->getAllAvailableRuleCollection();
?>
<div class="box">
	<div class="box-title">
		<h3><?php echo $this->__('Rule') ?></h3>
	</div>
	<?php if(!($ruleCollection->getItems())) : ?>
		<p class="note-msg"><?php echo $this->__('There is no rule available at this moment.'); ?></p>
	<?php else : ?>
		<?php echo $this->__('There are <strong>%s</strong> rule(s) available :', count($ruleCollection->getItems())) ?>
		<table class="data-table">
			<th><?php echo $this->__('#') ?></th>
			<th><?php echo $this->__('Title') ?></th>
			<th><?php echo $this->__('Description') ?></th>
			<th><?php echo $this->__('From Date') ?></th>
			<th><?php echo $this->__('To Date') ?></th>
			<th><?php echo Mage::helper('rewardpoint')->getUnitName() ?></th>
			<th><?php echo $this->__('Priority') ?></th>
			<?php foreach($ruleCollection->getData() as $rule) : ?>
			<tr>
				<!-- <td><?php // echo $rule->getId() ?></td>
				<td><?php // echo $rule->getTitle() ?></td>
				<td><?php // echo $rule->getDescription() ?></td>
				<td><?php // echo $rule->getFromDate() ?></td>
				<td><?php // echo $rule->getToDate() ?></td>
				<td><?php // echo $rule->getPointsEarned() ?></td>
				<td><?php // echo $rule->getPriority() ?></td> -->
				<td><?php echo $rule['rule_id'] ?></td>
				<td><?php echo $rule['title'] ?></td>
				<td><?php echo $rule['description'] ?></td>
				<td><?php echo date('Y-m-d', Mage::getModel('core/date')->timestamp($rule['from_date'])); ?></td>
				<td><?php echo date('Y-m-d', Mage::getModel('core/date')->timestamp($rule['to_date'])); ?></td>
				<td><?php echo $rule['points_earned'] ?></td>
				<td><?php echo $rule['priority'] ?></td>
			</tr>
			<?php endforeach; ?>
		</table>
	<?php endif; ?>
</div>