<?php if (Mage::helper('rewardpoint')->canGetReferralPoint()): ?>
<form action="<?php echo $this->getUrl('rewardpoint/invite/refer') ?>" method="post" id="refer_friend_form">
	<div class="fieldset">
		<h2 class="legend"><?php echo $this->__('Invitation Form') ?></h2>
		<ul class="form-list">
			<li class="fields">
				<label for="email" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>
				<div class="input-box">
					<input type="text" name="email" id="email" class="input-text required-entry validate-email" />
				</div>
			</li>
			<li class="fields">
				<label for="message"><?php echo $this->__('Invite Message') ?></label>
				<div class="input-box">
					<textarea id="message" name="message"></textarea>
				</div>
			</li>
			<button type="submit" title="<?php echo $this->__('Invite') ?>" class="button"><span><span><?php echo $this->__('Invite') ?></span></span></button>
		</ul>
	</div>
</form>
<script>
	var referForm = new VarienForm('refer_friend_form');
</script>
<?php else : ?>
<p class="note-msg"><?php echo $this->__('Limit reached. Today you can\'t invite anymore'); ?></p>
<?php endif ; ?>