<?php $unitName = Mage::helper('rewardpoint')->getUnitName();?>
<div class="box-account">
	<div class="box-head">
		<h2><?php echo $this->__('Referral System') ?></h2>
		<a href="<?php echo Mage::getUrl('rewardpoint/invite/view') ?>" style="float:right"><?php echo $this->__('View History')?></a>
	</div>
	<?php if(Mage::helper('rewardpoint')->isReferralSystemEnabled()) : ?>
	<p><b><?php echo $this->__('Invite your friend to the system to get reward points');?></b></p>
	<?php if ($pointPerFriend = Mage::getStoreConfig('rewardpoint/referal_system/point_earned_each_customer_registered')):?>
	<p> - <?php echo $this->__('Point for each referred friend: %s %s', $pointPerFriend, $unitName);?></p>
	<?php endif ?>
	<?php if (Mage::getStoreConfig('rewardpoint/referal_system/earn_point_from_referral_order')):?>
		<?php $type = (int) Mage::getStoreConfig('rewardpoint/referal_system/type');?>
		<?php $flat_rate = (int) Mage::getStoreConfig('rewardpoint/referal_system/flat_rate');?>
		<?php if ($type == 0):?>
			<p> - <?php echo $this->__('Rewarded %s %s for the first order made by referred friend', $flat_rate, $unitName);?></p>
		<?php else: ?>
			<p> - <?php echo $this->__('Rewarded %s %s for each order made by referred friend', $flat_rate, $unitName);?></p>
		<?php endif;?>			
	<?php endif ?>
	<?php echo $this->getChildHtml(); ?>
	<?php else : ?>
	<p class="note-msg"><?php echo $this->__('Referral System is now disabled.'); ?></p>
	<?php endif; ?>
</div>